### ISSUE TITLE
Meta issue: List of things to complete by end of August

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#81]
**NTH:** Nice To Have
**HP**: High Priority
**MP**: Medium Priority
**LP**: Low Priority

cc: @FatimaPillosu 

<hr />

**Checklist:**
- [x] [**HP**] Limit number of lines of logs streamed to the Electron process to `1000`.
- [x] [**HP**] Fix detection of predictor columns in the point data table
- [x] [**HP**] Allow user to input binning values for Forecast Error (FE)
- [x] [**HP**] Implement color coding for Forecast Error (FE) Mapping Functions
- [x] [**HP**] Allow users to save Mapping Functions generated from the suggested breakpoints.
- [x] [**MP**] Display Y-axis of Mapping Functions as a percentage
- [x] [**MP**] Add validation for `yLim` value to be an integer and between `0` and `100`.
- [x] [**LP**] Display a spinner while the point data table is being read.
- [x] [**LP**] Perform the validation of inputs for Kolmogorov-Smirnov test in JS for faster UX.
- [x] [**LP**] Display a spinner while the Kolmogorov-Smirnov test is performed.
- [x] [**LP**] Double check Local Solar Time (LST) computation
- [x] [**LP**] Allow uploading of breakpoints CSV file to pre-populate the threshold splits table.
- [x] [**LP**] Prevent namespace clashes between computation short-name and predictor code.
- [x] [**LP**] Display a spinner while the decision tree is being generated.
- [x] [**LP**] Display date in point data table in `YYYYMMDD` format.
- [x] [**LP**] Parameterize `N` for errors.csv file (currently hard-coded to `100`).
- [x] [**NTH**][**LP**] Different color coding for different predictors, so leaves at different levels can be visually distinguished.

**Comment by onyb** [comment]
The user is shown a spinner during loading of the point data table. This is useful especially when the point data table is huge. Screenshot below:


![spinner](https://user-images.githubusercontent.com/3684187/64069896-6e381880-cc54-11e9-97d2-d557a88aac3b.png)

**Comment by onyb** [comment]
Below is screenshot of how the user inputs the bins for FER / FE.

In case of FER, the value for bins is auto-filled with what you see in the screenshot. These values are editable, and the color coding for the histogram bars are adjusted accordingly (green for negative bins, white for the bin crossing origin, yellow for the 5 bins after the white bin, and red for the rest).


In case of FE, the user starts with a blank field. The color coding (blue, white, red) is adjusted according to the bins input by the user.

We're also displaying some stats about the point data table to help the user come up with meaningful bin values.

![loaded](https://user-images.githubusercontent.com/3684187/64069918-f3233200-cc54-11e9-986a-7f664c428c61.png)

**Comment by onyb** [comment]
Leaf nodes in the decision tree are now color coded with a gradient of R-G-B from top to bottom, automatically adjusted depending upon the number of predictors.

The root node initially has a "black" stroke with "white" fill.

![decision-tree](https://user-images.githubusercontent.com/3684187/64075449-d3bdf080-ccb8-11e9-9172-78d9b818a4b6.png)

**Comment by onyb** [comment]
If a user tries to load a huge breakpoints CSV file, the generation and rendering of the decision tree could take several seconds. A dimmer and loader is displayed to prevent the user from triggering additional actions until the rendering is complete. Screenshot below:

![dt](https://user-images.githubusercontent.com/3684187/64076463-86944b80-ccc5-11e9-896d-0f7370eeb76e.png)

**Comment by onyb** [comment]
User can now enter the number of columns to use while saving the mapping functions as CSV. Screenshot below:
![error](https://user-images.githubusercontent.com/3684187/64076851-7337af00-ccca-11e9-8cd1-8639a7065457.png)
