### ISSUE TITLE
Read observations metadata

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#90]
The new geopoints format has a metadata section as follows:

```
#METADATA
date=20190101
k=43200
step=0
time=0000
units=mm
```

**TODOs:**
- [x] Extract geopoints metadata using metview-python library.
  * If feature is not supported, implement it upstream.
  * Write unit-tests.
- [x] Expose the metadata via an endpoint on the backend.
- [x] Display the metadata on the frontend, and autofill fields whenever possible.

**Comment by onyb** [comment]
Fixed in [v0.21.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.21.0).
