### ISSUE TITLE
Consider using gRPC for communication between backend and Electron app

### ISSUE THREAD

**Issue by onyb** [esowc/ecPoint-Calibrate#91]
Currently, the backend exposes an HTTP-based REST API, which allows the GUI to get information or provide tasks to the backend.

This mechanism is very inefficient due to the nature of data exchanged between the backend and the Electron app, which is often large arrays, and byte arrays. A much better alternative is [gRPC](https://grpc.io) by Google. It uses HTTP/2-based transport, has much better performance, and uses a [rich serialization format](https://developers.google.com/protocol-buffers) that prevents type errors.

Another useful feature is that it supports **cancellation**. This will allow the user to stop computations at any moment.

**TODOs:**
- [ ] Define gRPC interface for the backend and frontend, using Protocol Buffer format.
- [ ] Replace the Rest API with a gRPC service.
- [ ] Implement cancellation.
- [ ] Setup grpc-node and translate old axios calls to use the same.

**Comment by FatimaPillosu** [comment]
@onyb , can thi issue be closed?
Cheers,
Fatima

**Comment by onyb** [comment]
Yes. Just for posterity, gRPC is a Remote Procedure Call (RPC) framework that uses Protocol Buffers as the serialization format.

gRPC client on the frontend is not something that is commonly used or known to be stable. The current RESTful interface is ideal for an application like this, although a good improvement would be to have strict contracts on the backend, which brings some of the advantages of gRPC.
